const DEFAULT_CONSUMABLE_ICON = 'https://i.imgur.com/znqb9PK.png';

const CONSUMABLE_ICON_BY_NAME: Record<string, string> = {
  'Spirit of Zanza': 'https://i.imgur.com/yR4I9d1.png',
  'Elixir of the Mongoose': 'https://i.imgur.com/3OMD7An.png',
  'Elixir of Giants': 'https://i.imgur.com/u59jc8n.png',
  'JUJU Power': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_monsterscales_11.jpg',
  'Juju Might': 'https://i.imgur.com/9tbn9Pj.png',
  'Winterfall Firewater': 'https://i.imgur.com/7Mr25Uh.png',
  'Elixir of Fortitude': 'https://i.imgur.com/Um0YrK5.png',
  'Elixir of Superior Defense': 'https://i.imgur.com/3oe8QT3.png',
  'Gift of Arthas': 'https://i.imgur.com/YTQnr8j.png',
  'Ground Scorpok Assay': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_dust_02.jpg',
  'Nordanaar Herbal Tea': 'https://i.imgur.com/WfOqPc7.png',
  'Major Healing Potion': 'https://i.imgur.com/gj8Kjh6.jpeg',
  'Greater Stoneshield Potion': 'https://i.imgur.com/UQxsZlT.png',
  'Free Action Potion': 'https://i.imgur.com/JGqwsMM.png',
  'Hardened Mushroom': 'https://i.imgur.com/UVoXWpl.png',
  'Le Fishe Au Chocolat': 'https://i.imgur.com/FloShsU.png',
  'Gurubashi Gumbo': 'https://i.imgur.com/gJyCzq9.png',
  'Rumsey Rum Black Label': 'https://i.imgur.com/mTJ6iae.png',
  'Medivh’s Merlot': 'https://i.imgur.com/qDiBZEP.png',
  "Medivh's Merlot": 'https://i.imgur.com/qDiBZEP.png',
  'Elemental Sharpening Stone': 'https://i.imgur.com/DWesM4y.png',
  'R.O.I.D.S.': 'https://wow.zamimg.com/images/wow/icons/large/inv_stone_15.jpg',
  'Power Mushroom': 'https://i.imgur.com/hmHxG8S.png',
  'Danonzo’s Tel’Abim Medley': 'https://i.imgur.com/opj1isB.png',
  "Danonzo's Tel'Abim Medley": 'https://i.imgur.com/opj1isB.png',
  'Consecrated Sharpening Stone': 'https://wow.zamimg.com/images/wow/icons/large/inv_stone_sharpeningstone_02.jpg',
  'Brilliant Mana Oil': 'https://i.imgur.com/CHUanYG.png',
  'Cerebral Cortex Compound': 'https://wow.zamimg.com/images/wow/icons/large/inv_potion_32.jpg',
  'Major Mana Potion': 'https://i.imgur.com/5zsiUu3.png',
  'Danonzo’s Tel’Abim Surprise': 'https://i.imgur.com/6geeYTM.png',
  "Danonzo's Tel'Abim Surprise": 'https://i.imgur.com/6geeYTM.png',
  'Brilliant Wizard Oil': 'https://i.imgur.com/Yv0IhAw.png',
  'Mageblood Potion': 'https://i.imgur.com/yR4I9d1.png',
  'Greater Arcane Elixir': 'https://i.imgur.com/VQvI7xv.png',
  'Elixir of Shadow/Fire/Frost Power': 'https://wow.zamimg.com/images/wow/icons/large/inv_potion_46.jpg',
  'Dreamshard Elixir': 'https://i.imgur.com/33o6DrC.png',
  'Dreamtonic': 'https://wow.zamimg.com/images/wow/icons/large/inv_potion_10.jpg',
  'Juice Striped Melon': 'https://i.imgur.com/k2cAn1D.png',
  'Nightfin Soup': 'https://i.imgur.com/rA9SWdY.png',
  'Danonzo’s Tel’Abim Delight': 'https://i.imgur.com/rA9SWdY.png',
  "Danonzo's Tel'Abim Delight": 'https://i.imgur.com/rA9SWdY.png',
  'Medivh’s Merlot Blue': 'https://i.imgur.com/eX86Sbx.png',
  "Medivh's Merlot Blue": 'https://i.imgur.com/eX86Sbx.png',
  'Blessed Wizard Oil': 'https://wow.zamimg.com/images/wow/icons/large/inv_potion_26.jpg',
  'Superior Mana Potion': 'https://i.imgur.com/1bjgiwl.png',
  'Greater Fire Protection Potion (MC/BWL/Naxx)': 'https://i.imgur.com/sGfAXKi.png',
  'Greater Arcane Protection Potion': 'https://i.imgur.com/g7SPUFw.png',
  'Greater Nature Protection Potion': 'https://i.imgur.com/vufTUog.png',
  'Greater Shadow Protection Potion': 'https://i.imgur.com/5gr4BYj.png',
  'Greater Frost Protection Potion': 'https://i.imgur.com/UbGnTPN.png',
  'Nature Protection Potion': 'https://wow.zamimg.com/images/wow/icons/large/inv_potion_06.jpg',
  'Purification Potion': 'https://wow.zamimg.com/images/wow/icons/large/inv_potion_31.jpg',
  'Restorative Potion': 'https://i.imgur.com/gZOfzGT.png',
  'Hourglass Sand': 'https://i.imgur.com/jVejsTr.png',
  'Frozen Rune': 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_rune_09.jpg',
  'Frost Oil': 'https://i.imgur.com/UbGnTPN.png',
  'Goblin Sapper Charge': 'https://i.imgur.com/u8qDu3I.png',
  'Ez-Thro Dynamite II': 'https://i.imgur.com/dNqpfnf.png',
  'Oil of Immolation': 'https://i.imgur.com/1ANm5Zi.png',
  'Swiftness Potion': 'https://i.imgur.com/86XQQo4.png',
  'Limited Invulnerability Potion': 'https://i.imgur.com/5en8lBc.png',
  'Lucidity Potion': 'https://i.imgur.com/UbGnTPN.png'
};

export const getConsumableIcon = (name: string) => CONSUMABLE_ICON_BY_NAME[name] || DEFAULT_CONSUMABLE_ICON;
